
export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $bannerSlider: document.querySelector('.banner-slider'),
  $marketing: document.querySelector('.marketing'),
  $blogSlider: document.querySelector('.blog-content__slider'),
  $catalogSlider: document.querySelector('.hero-catalog__slider'),
  $catalogFiltersTop: document.querySelectorAll('.catalog-filter__top'),
  $hideFilters: document.querySelector('.hide-filters'),
  $catalogColumns: document.querySelector('.catalog-columns__list'),
  $catalogGridContent: document.querySelector('.catalog-grid__content'),
  $catalogFilter: document.querySelectorAll('.catalog-filter'),
  $catalogFilterItems: document.querySelectorAll('.catalog-filter__item'),
  $catalogChoice: document.querySelector('.catalog-choice'),
  $customSelect: document.querySelectorAll('.custom-select'),
  $freeDeliveryBtn: document.querySelector('.free-delivery__btn'),
  $colorSelect: document.querySelector('.color-select'),
  $sizeSelect: document.querySelector('.size-select'),
  // $sizeSelectCheckbox: document.querySelector('.size-select__checkbox'),
  $stepper: document.querySelector('.stepper'),
  $cardSliderThumbs: document.querySelector('.card-slider__thumbs'),
  $sliderImg: document.querySelector('.card-slider__main img'),
  $cardDescrLink: document.querySelectorAll('.card-description__link'),
  $cardRelatedSlider: document.querySelector('.card-related__slider'),
  $burger: document.querySelector('.burger'),
  $cart: document.querySelector('.cart'),
  $navClose: document.querySelector('.nav__close'),
  $nav: document.querySelector('.nav'),
  $mobileFiltersOpen: document.querySelector('.catalog-mobile-filters'),
  $catalogFilters: document.querySelector('.catalog-filters'),

}
